server:
  port: 3000

spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:nacos}:${NACOS_PORT:8848}
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
  config:
    import:
      - nacos:application-${spring.profiles.active}.yml
      - nacos:${spring.application.name}-${spring.profiles.active}.yml
  profiles:
    active: @profiles.active@

