server:
  port: 9999
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: 123.60.165.53:8848
      config:
        server-addr: 123.60.165.53:8848
  config:
    import:
      - optional:nacos:nacos-config-${spring.profiles.active}.yml
      - optional:nacos:${spring.application.name}-${spring.profiles.active}.yml

  profiles:
    active: @profiles.active@
